name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@use_py_310
    with:
      commit_sha: ${{ github.sha }}
      package: competitions
      package_name: competitions
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
